baseURL = "https://tryidea.github.io/blog/"
languageCode = "zh-CN"
title = "try's site"
theme = "yinwang"
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = false
#pygmentsStyle = "dracula"
#pygmentsOptions = ['linenos']
# 代码高亮/chroma，hugo默认自带（可选）
                                                    
[params]
    author = "dufugang"
    github = "tryIdea"
    googleAnalytics = "UA-128555056-1" # 谷歌统计gtag
    highlight = "atom-one-dark" # 默认样式 `github`
    langs = ["go"]
    # 默认加载 highlight.min.js，但 一些不支持的语言, 你自己添加,
    # 其实也可以使用hugo自带的语法高亮器设置，不过我有点懒
    # single = false # 单页面的Home 按钮去除
    # menus = true # 想加更多目录，具体请看常见问题中的更多配置
    backgroundColor = "#fbf6ec" # 加点黄黄的背景色
    githubRepo = "https://github.com/tryIdea/try "
    editBtn = true # 两个字段一起，才能搞好编辑按钮
